### ISSUE TITLE
Updated temperature to show in Celsius

### ISSUE THREAD

**Issue by MagnusTim** [SolidifyDemo/the-weather-app#2]
As a user I want to read the temperature in Celsius degrees

```[tasklist]
### Tasks
- [ ] Run the conversion to show in Celsius
- [ ] Document the new updates in the file
- [ ] Add related tests
- [ ] Update the documentation of the repository
```
